### ISSUE TITLE
need storageclass if not defined

### ISSUE THREAD

**Issue by rootfs** [kbsingh/devshift-looper#2]
for 3.5
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
```
